arb-dir: lib/presentation/app/l10n/
template-arb-file: app_es.arb
output-localization-file: app_localizations.dart
nullable-getter: false
synthetic-package: false
untranslated-messages-file: missing_translations.txt
format: true